version: '2'
services:
    gastronomee-app:
        image: gastronomee
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://gastronomee-postgresql:5432/gastronomee
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=gastronomee-elasticsearch:9300
        ports:
            - 8080:8080
    gastronomee-postgresql:
        extends:
            file: postgresql.yml
            service: gastronomee-postgresql
    gastronomee-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: gastronomee-elasticsearch
